### ISSUE TITLE
[FEA] Only config subset of nodes in a certain mode.

### ISSUE THREAD

**Issue by ZhenshengLee** [micro-ROS/system_modes#95]
Hi, first of all I want to say this is a great project to manage lifecycle nodes!

There'a a need to config the lifecycle state of only a subset of nodes in one mode, but config another subset of nodes in other modes.

Let's say, can the following config work? (Currently I don't need the extra parameter-based modes either)

```yaml
# system modes example
---

actuation:
  ros__parameters:
    type: system
    parts:
      manipulator
      drive_base
    modes:
      __DEFAULT__:
        manipulator: inactive
        drive_base: inactive
      MODERATE:
        manipulator: active
      PERFORMANCE:
        drive_base: active
```

Thanks!
