### ISSUE TITLE
[FEA] Allow deactivating nodes when system is activated.

### ISSUE THREAD

**Issue by ZhenshengLee** [micro-ROS/system_modes#96]
There is a need to selectively disable the function of a node, that's say deactivating a node in a certain system mode.

Should the following config work? Thanks!

```yaml
---

actuation:
  ros__parameters:
    type: system
    parts:
      drive_base
      left/manipulator
      right/manipulator
    modes:
      __DEFAULT__:
        drive_base: active.__DEFAULT__
        left/manipulator: inactive
        right/manipulator: inactive
      MODERATE:
        drive_base: active.__DEFAULT__
        left/manipulator: inactive
        right/manipulator: active
      PERFORMANCE:
        drive_base: active.__DEFAULT__
        left/manipulator: active.__DEFAULT__
        right/manipulsator: inactive

left/manipulator:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          max_torque: 0.1
      WEAK:
        ros__parameters:
          max_torque: 0.1
      STRONG:
        ros__parameters:
          max_torque: 0.2

drive_base:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          max_speed: 0.1
          controller: PID
      SLOW:
        ros__parameters:
          max_speed: 0.2
          controller: PID
      FAST:
        ros__parameters:
          max_speed: 0.9
          controller: MPC

right/manipulator:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          max_torque: 0.11
      WEAK:
        ros__parameters:
          max_torque: 0.05
      STRONG:
        ros__parameters:
          max_torque: 0.3
```
