### ISSUE TITLE
Error in node state when switching modes

### ISSUE THREAD

**Issue by Juancams** [micro-ROS/system_modes#99]
Hello!

I've been working with system_modes for a few days and I'm having an error when changing my system mode.

I have several modes, which are default, alert, compromised and halt, and in this particular example when I change the mode from alert to compromised there are nodes that do not change their status from active to inactive. I leave you images of the monitor so that you can see the result together with the yaml configuration of both modes.

```
ALERT:
        image_1_to_2: inactive
        imu_1_to_2: active
        odom_1_to_2: active
        pc2_1_to_2: active
        scan_1_to_2: active
        tf_1_to_2: active
        tf_static_1_to_2: active
        twist_2_to_1: active
COMPROMISED:
        image_1_to_2: inactive
        imu_1_to_2: active
        odom_1_to_2: active
        pc2_1_to_2: inactive
        scan_1_to_2: inactive
        tf_1_to_2: active
        tf_static_1_to_2: active
        twist_2_to_1: inactive
```
System in alert mode:
![Screenshot from 2022-12-20 11-08-47](https://user-images.githubusercontent.com/44479765/208641297-4330e612-6507-4f02-9892-7e2adf2c8fac.png)

System in compromised mode:
![Screenshot from 2022-12-20 11-08-36](https://user-images.githubusercontent.com/44479765/208641324-70392290-c993-4d99-baf2-d1b1c37923e1.png)

I also show you how I have configured the modes of some of the nodes, although I am not using that parameter

```
pc2_1_to_2:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          use_sim_time: false
      
scan_1_to_2:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          use_sim_time: false
```

I do not have any type of rule configured, although I suppose that for this simple case of changing node states it would not be necessary.

Any idea what is happening?
